[package]

name = "tinfo"
version = "0.5.0"
authors = ["Richo Healey <richo@psych0tik.net>"]
license = "MIT"
repository = "https://github.com/richo/tinfo-rs"
description = "A frontend to manipulating tmux"

[dependencies]

regex = "*"
getopts = "*"
lazy_static = "*"
