[package]

name = "tinfo"
version = "0.6.0"
authors = ["Richo Healey <richo@psych0tik.net>"]
license = "MIT"
repository = "https://github.com/richo/tinfo-rs"
description = "A frontend to manipulating tmux"

[dependencies]

regex = "1.0.5"
getopts = "0.2.18"
lazy_static = "1.1.0"
